init:
  - git config --global core.autocrlf true
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: off
os: Visual Studio 2017
before_build:
  - cmd: dotnet restore Configuration.MongoDb.sln
build_script:
  - msbuild Configuration.MongoDb.sln /p:Configuration=Release
  - msbuild cibuild.proj /p:Configuration=Release
version: '1.0.{build}'
dotnet_csproj:
  patch: true
  file: 'src\**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
artifacts:
  - path: 'src\Midmid.Configuration.MongoDb\nupkg\*.nupkg'
    name: Midmid.Configuration.MongoDb
    type: .nupkg
deploy:
  - provider: NuGet
    server: https://my.nuget.server/feed
    api_key:
      secure: JqkPzMaEgaWCJqqIuOdnqOp6WI7H6RiJxx6+dBKaXb9L8dJ0xgQI03YVSndhv/eh
    skip_symbols: true
    artifact: 'src\Midmid.Configuration.MongoDb\nupkg\*.nupkg'
